name: openwebui

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "${OPENWEBUI_PORT:-8080}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_NAME=${WEBUI_NAME}
      - WEBUI_AUTH=${WEBUI_AUTH:-True}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-True}
      - DEFAULT_USER_ROLE=${DEFAULT_USER_ROLE:-user}
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - openwebui-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama:/root/.ollama
    env_file:
      - .env.local
    networks:
      - openwebui-network
    restart: unless-stopped
    # Décommentez les lignes suivantes si vous avez un GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  openwebui-network:
    driver: bridge

volumes:
  open-webui:
    driver: local
  ollama:
    driver: local 