version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui-production
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "127.0.0.1:${OPENWEBUI_PORT:-8080}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_NAME=${WEBUI_NAME}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - DEFAULT_USER_ROLE=${DEFAULT_USER_ROLE}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENABLE_LOGIN_FORM=${ENABLE_LOGIN_FORM}
      - ENABLE_OAUTH_SIGNUP=${ENABLE_OAUTH_SIGNUP}
      - ENABLE_COMMUNITY_SHARING=${ENABLE_COMMUNITY_SHARING}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_DB_PATH=/app/backend/data/vector_db
      - SENTENCE_TRANSFORMERS_HOME=/app/backend/data/cache
      - TRANSFORMERS_CACHE=/app/backend/data/cache
      - CHUNK_SIZE=${CHUNK_SIZE:-1500}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-150}
    env_file:
      - .env.prod
    networks:
      - openwebui-network
    restart: unless-stopped
    # Configuration pour la production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Limites de ressources pour la production (compatible Docker Compose standalone)
    mem_limit: 4G
    cpus: "2.0"
    mem_reservation: 512M

networks:
  openwebui-network:
    driver: bridge

volumes:
  open-webui:
    driver: local 